package org.xrpl.xrpl4j.crypto.mptcryptowasm;

/*-
 * ========================LICENSE_START=================================
 * xrpl4j :: core
 * %%
 * Copyright (C) 2020 - 2023 XRPL Foundation and its contributors
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =========================LICENSE_END==================================
 */

import java.util.Arrays;
import java.util.Objects;

/**
 * Represents an ElGamal keypair generated by the WASM module.
 *
 * <p>This is the WASM equivalent of {@link org.xrpl.xrpl4j.crypto.mpt.elgamal.ElGamalKeyPair}
 * from David's BouncyCastle-based implementation.</p>
 *
 * <p>Key differences:</p>
 * <ul>
 *   <li>David's version stores the public key as a BouncyCastle {@code ECPoint}</li>
 *   <li>This version stores the public key as raw bytes (33-byte compressed format)</li>
 * </ul>
 */
public final class WasmElGamalKeyPair {

  private final byte[] privateKey;
  private final byte[] publicKey;

  /**
   * Constructs a new WasmElGamalKeyPair.
   *
   * @param privateKey The 32-byte private key.
   * @param publicKey  The 33-byte compressed public key.
   */
  public WasmElGamalKeyPair(byte[] privateKey, byte[] publicKey) {
    Objects.requireNonNull(privateKey, "privateKey must not be null");
    Objects.requireNonNull(publicKey, "publicKey must not be null");

    if (privateKey.length != 32) {
      throw new IllegalArgumentException("privateKey must be 32 bytes, got " + privateKey.length);
    }
    if (publicKey.length != 33) {
      throw new IllegalArgumentException("publicKey must be 33 bytes (compressed), got " + publicKey.length);
    }

    this.privateKey = Arrays.copyOf(privateKey, privateKey.length);
    this.publicKey = Arrays.copyOf(publicKey, publicKey.length);
  }

  /**
   * Gets the private key.
   *
   * @return A copy of the 32-byte private key.
   */
  public byte[] privateKey() {
    return Arrays.copyOf(privateKey, privateKey.length);
  }

  /**
   * Gets the public key in compressed format.
   *
   * @return A copy of the 33-byte compressed public key.
   */
  public byte[] publicKey() {
    return Arrays.copyOf(publicKey, publicKey.length);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WasmElGamalKeyPair that = (WasmElGamalKeyPair) o;
    return Arrays.equals(privateKey, that.privateKey) &&
      Arrays.equals(publicKey, that.publicKey);
  }

  @Override
  public int hashCode() {
    int result = Arrays.hashCode(privateKey);
    result = 31 * result + Arrays.hashCode(publicKey);
    return result;
  }

  @Override
  public String toString() {
    // Only show public key for security
    return "WasmElGamalKeyPair{publicKey=" + bytesToHex(publicKey) + "}";
  }

  private static String bytesToHex(byte[] bytes) {
    StringBuilder sb = new StringBuilder();
    for (byte b : bytes) {
      sb.append(String.format("%02x", b));
    }
    return sb.toString();
  }
}

